services:
  - type: web
    name: barbershop-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
    branch: main
    rootDir: .
    disk:
      name: barbershop-data
      mountPath: /opt/render/project/src
      sizeGB: 1

